name: Update Homebrew Cask

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install requests lxml
          
      - name: Update Eligere cask
        run: |
          python3  update.py         

      - name: Check if update was made
        id: check_update
        run: |
          if [ -f update_needed.txt ]; then
            UPDATE_NEEDED=$(cat update_needed.txt)
            echo "update_needed=$UPDATE_NEEDED" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.ACTION_TOKEN }}
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add Casks/eligere.rb
          
          NEW_VERSION=$(grep -o 'version "[^"]*"' Casks/eligere.rb | cut -d'"' -f2)
          
          git commit -m "Update Eligere to version $NEW_VERSION"
          
          git push origin main
          
      - name: Create release notes
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          NEW_VERSION=$(grep -o 'version "[^"]*"' Casks/eligere.rb | cut -d'"' -f2)
          echo "✅ Successfully updated Eligere cask to version $NEW_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- Updated version and SHA256 hash" >> $GITHUB_STEP_SUMMARY
          echo "- Changes committed to main branch" >> $GITHUB_STEP_SUMMARY
